print("==================================================")
print("hello world!")
print("this is my first python program coded on mac")
print("mac is amazing for coder")
print("==================================================")
print("now i'm trying edit the file in github.com")
print(str(4*5))
