print("==================================================")
print("hello world!")
print("this is my first python program coded on mac")
print("mac is amazing for coder")
print("==================================================")
print("now i'm tring edit the file in github.com")
